name: matching
description: Every matcher for your tests you have been missing.
version: 0.1.0
repository: https://github.com/alexeyinkin/dart-matching

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.25.5
