name: matching
description: Every single matcher for your tests that you have been missing.
version: 0.1.3
repository: https://github.com/alexeyinkin/dart-matching

topics:
  - test

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.25.5

dev_dependencies:
  total_lints: ^3.4.0
